app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Route::get('/', 'WelcomeController@index');
Route::get('', 'HomeController@index');
Route::get('home', 'HomeController@index');
Route::get('modalidad-de-grado','HomeController@modalidad');
Route::get('estado-trabajo-de-grado','HomeController@estadotg');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::group(['prefix'=>'gestionar','middleware'=>['auth'], 'namespace'=>'Gestionar'], function(){	
	
	Route::resource('estudiante','EstudiantesController');
	Route::resource('profesor','ProfesoresController');
	Route::resource('secretaria','secretariaController');
	Route::resource('director','directorController');
	Route::resource('decano','decanoController');

	Route::resource('trabajo-de-grado','TrabajoDeGradoController');
	Route::resource('proceso-trabajo-de-grado','ProcesoTGController');

});

Route::group(['prefix'=>'admin','middleware'=>['auth'], 'namespace'=>'Admin'], function(){	
	Route::resource('modalidad','ModalidadController');
	Route::resource('estado','EstadoController');
});


Route::get('proceso-trabajo-de-grado/{idTG}',['as'=>'gestionar.proceso-trabajo-de-grado.lista','uses'=>'Gestionar\ProcesoTGController@lista']);

resources/views/table/tabla-estadostg.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">Tabla de Estadoss</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal">
		@if( Auth::user()->type == 'Admin' )
			{!! Form::open(['route' => 'admin.estado.store', 'method'=>'POST', 'class'=>'']) !!}
				<div class="col-lg-12" style='padding-bottom: 5px;'>	        
			        {!! Form::label('estado', 'Ingrese un nuevo Estado', ['class'=>'']) !!}
			        {!! Form::text('estado', null, ['class'=>'form-control', 'placeholder'=>"Ingrese un nuevo Estado"]) !!}
			    </div>
			    <div class="col-lg-3 col-lg-offset-9">
			    	<button type="submit" class="btn btn-success">Añadir</button>
			    </div>
			{!! Form::close() !!}
			@endif
		<table class='table table-hover'>
		    <tr>
		        <th>Codigo</th>
				<th>Estado</th>
		    </tr>
		    @foreach ($estadostg as $estadotg)
				<tr>
					<td>{{ $estadotg->id }}</td>
					<td>{{ $estadotg->estado }}</td>		            
				</tr>
		    @endforeach
		</table>
	</div>
</div>

resources/views/table/tabla-estudiantes.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('menu') }}</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal table-responsive">
		<table id="tabla-estudiante" class='table table-bordered table-striped'>
		    <thead>
			    <tr>
			        <th>Codigo</th>
					<th>Identificacion</th>				
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Fecha Nacimiento</th>
					<th>Direccion</th>
					<th>Barrio</th>
					<th>Celular</th>
					<th>Emai</th>
					@if(Auth::user()->type != 'Docente')
						<th>Editar</th>
						<th>Eliminar</th>
					@endif
			    </tr>
		    </thead>
		    <tbody>
		    @foreach ($estudiante as $estudiantes)
				<tr>
					<td>{{ $estudiantes->codigo }}</td>
					<td>{{ $estudiantes->identificacion }}</td>
					<td>{{ $estudiantes->nombre1 }} {{ $estudiantes->nombre2 }}</td>
					<td>{{ $estudiantes->apellido1 }} {{ $estudiantes->apellido2 }}</td>
					<td>{{ $estudiantes->fechaNac }}</td>
					<td>{{ $estudiantes->direccion }}</td>
					<td>{{ $estudiantes->barrio }}</td>
					<td>{{ $estudiantes->celular }}</td>
					<td>{{ $estudiantes->email }}</td>
		            @if(Auth::user()->type != 'Docente')
			            <td>
			                <a class='btn btn-success' href="{{ route('gestionar.estudiante.edit',$estudiantes->id) }}">Editar</a>
			            </td>
			            <td>
				            {!! Form::open(['route' => ['gestionar.estudiante.destroy', $estudiantes->id], 'method'=>'DELETE', 'class'=>'', 'id'=>'delete_estudiante']) !!}
				            	<button type="submit" class="btn btn-danger">Eliminar</button>
			                {!! Form::close() !!}
			            </td>
					@endif
				</tr>
		    @endforeach
		    </tbody>
		    <tfoot>
			    <tr>
			        <th>Codigo</th>
					<th>Identificacion</th>				
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Fecha Nacimiento</th>
					<th>Direccion</th>
					<th>Barrio</th>
					<th>Celular</th>
					<th>Emai</th>
					@if(Auth::user()->type != 'Docente')
						<th>Editar</th>
						<th>Eliminar</th>
					@endif
			    </tr>
		    </tfoot>
		</table>
	</div>
</div>

resources/views/table/tabla-modalidades.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">Tabla de Modalidades</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal table-responsive">
		<div class="row">
			@if( Auth::user()->type == 'Admin' )
			{!! Form::open(['route' => 'admin.modalidad.store', 'method'=>'POST', 'class'=>'']) !!}
				<div class="col-lg-12" style='padding-bottom: 5px;'>	        
			        {!! Form::label('moalidad', 'Ingrese una nueva Modalidad', ['class'=>'']) !!}
			        {!! Form::text('descripcion', null, ['class'=>'form-control', 'placeholder'=>"Ingrese una nueva Modalidad"]) !!}
			    </div>
			    <div class="col-lg-3 col-lg-offset-9">
			    	<button type="submit" class="btn btn-success">Añadir</button>
			    </div>
			{!! Form::close() !!}
			@endif
		</div>
		<table class='table table-hover'>
		    <tr>
		        <th>Codigo</th>
				<th>Modalidad</th>
		    </tr>
		    @foreach ($modalidades as $modalidad)
				<tr>
					<td>{{ $modalidad->id }}</td>
					<td>{{ $modalidad->descripcion }}</td>		            
				</tr>
		    @endforeach
		</table>
	</div>
</div>

resources/views/table/tabla-proceso-trabajo-de-grado.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('menu') }}</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal table-responsive">
		<table class='table table-hover'>
		    <tr>
		        <th>ID</th>
				<th>Fecha</th>				
				<th>Titulo</th>
				<th>Modalidad</th>
				<th>Director</th>
				<th>Estudiante1</th>
				<th>Estudiante2</th>
				<th>Jurado1</th>
				<th>Jurado2</th>
				<th>Estado</th>
				<th>Radicado</th>
				<th>Acta de Sustentacion</th>
				<th>Fecha de Sustentacion</th>
		    	@if(Auth::user()->type == 'Admin' || Auth::user()->type == 'Director')
		    	<th>Editar</th>
		    	@endif
		    </tr>
				<tr>
					<td>{{ $trabajoG->id }}</td>
					<td>{{ $trabajoG->fecha }}</td>
					<td>{{ $trabajoG->titulo }}</td>
					<td>{{ $trabajoG->modalidadGrado }}</td>
					<td>{{ $trabajoG->director }}</td>
					<td>{{ $trabajoG->estudiante1 }}</td>
					<td>{{ $trabajoG->estudiante2 }}</td>
					<td>{{ $trabajoG->jurado1 }}</td>
					<td>{{ $trabajoG->jurado2 }}</td>
					<td>{{ $trabajoG->estado }}</td>
					<td>{{ $trabajoG->radicado }}</td>
					<td>{{ $trabajoG->actaSustentacion }}</td>
					<td>{{ $trabajoG->fechaSustentacion }}</td>
					@if(Auth::user()->type == 'Admin' || Auth::user()->type == 'Director')
					<td>
		                <a class='btn btn-success' href="{{ route('gestionar.trabajo-de-grado.edit',$trabajoG->id) }}">Editar</a>
		            </td>
		            @endif		            
				</tr>
		</table>
	</div>
</div>

<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('subMenu') }}</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal">
		{!! Form::open(['route' => 'gestionar.proceso-trabajo-de-grado.store', 'method'=>'POST', 'class'=>'','style'=>"padding-bottom: 20px;"]) !!}

			@include('form.form-acta-de-comite')

			<button type="submit" class="btn btn-lg btn-success">Registrar Acta</button>

		{!! Form::close() !!}
		<?php $i = 0 ?>
		@foreach ($procesoTG as $proceso)
			<?php $i = $i+1 ?>
			@if($i == count($procesoTG))
				<div class="well col-lg-12">
					<p>{{ $proceso->decision }}</p>
					{!! Form::model($proceso, ['route' => ['gestionar.proceso-trabajo-de-grado.update', $proceso->id], 'method'=>'PUT', 'class'=>'']) !!}					
						@include('form.form-editar-acta-comite')
						<div class="col-lg-2 col-lg-offset-10">
							<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalComite">
	  						Editar
							</button>
						</div>
					{!! Form::close() !!}
				</div>
			@else
				<div class="well">
					<span class="label label-success pull-right">
						{{ $proceso->updated_at->format('d/m/Y') }}
					</span>
					<p>{{ $proceso->decision }}</p>
				</div>
			@endif
		@endforeach
		<!-- Button trigger modal -->



	</div>
</div>

resources/views/table/tabla-profesores.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('menu') }}</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal table-responsive">
		<table id="tabla-docente" class='table table-bordered table-striped'>
		    <thead>
		    <tr>
		        <th>ID</th>
				<th>Identificacion</th>				
				<th>Nombres</th>
				<th>Apellidos</th>
				<th>Email</th>
				<th>Celular</th>
				<th>Fecha Nacimiento</th>
				<th>Pregrado</th>
				<th>Especializacion</th>
				<th>Maestria</th>
				<th>Doctorado</th>
				<th>Programa</th>
				@if(Auth::user()->type != 'Docente')
					<th>Editar</th>
					<th>Eliminar</th>
				@endif
		    </tr>
		    </thead>
		    <tbody>
		    @foreach ($profesores as $profesor)
				<tr>
					<td>{{ $profesor->id }}</td>
					<td>{{ $profesor->identificacion }}</td>
					<td>{{ $profesor->nombre1 }} {{ $profesor->nombre2 }}</td>
					<td>{{ $profesor->apellido1 }} {{ $profesor->apellido2 }}</td>
					<td>{{ $profesor->email }}</td>
					<td>{{ $profesor->celular }}</td>
					<td>{{ $profesor->fechaNac }}</td>
					<td>{{ $profesor->pregrado }}</td>
					<td>{{ $profesor->especializacion }}</td>
					<td>{{ $profesor->maestria }}</td>
					<td>{{ $profesor->doctorado }}</td>
					<td>{{ $profesor->programa->nombre }}</td>
					@if(Auth::user()->type != 'Docente')
			            <td>
			                <a class='btn btn-success' href="{{ route('gestionar.profesor.edit',$profesor->id) }}">Editar</a>
			            </td>
			            <td>
				            {!! Form::open(['route' => ['gestionar.profesor.destroy', $profesor->id], 'method'=>'DELETE', 'class'=>'', 'id'=>'delete_profesor']) !!}
				            	<button type="submit" class="btn btn-danger">Eliminar</button>
			                {!! Form::close() !!}
			            </td>
			        @endif
				</tr>
		    @endforeach
		    </tbody>
		</table>
	</div>
</div>	

resources/views/table/tabla-secretaria.blade.php
 
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('menu') }}</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body form-horizontal">
		<table id="tabla-secretaria" class='table table-bordered table-striped'>
		    <thead>
			    <tr>
			        <th>ID</th>
					<th>Identificacion</th>				
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Email</th>
					<th>Celular</th>
					<th>Fecha Nacimiento</th>
					<th>Programa</th>
					<th>Editar</th>
					<th>Eliminar</th>
			    </tr>
			</thead>
			<tbody>
		    @foreach ($secretarias as $secretaria)
				<tr>
					<td>{{ $secretaria->id }}</td>
					<td>{{ $secretaria->identificacion }}</td>
					<td>{{ $secretaria->nombre1 }} {{ $secretaria->nombre2 }}</td>
					<td>{{ $secretaria->apellido1 }} {{ $secretaria->apellido2 }}</td>
					<td>{{ $secretaria->email}}</td>
					<td>{{ $secretaria->celular }}</td>
					<td>{{ $secretaria->fechaNac }}</td>
					<td> {{ $secretaria->programa->nombre }} </td>
		            <td>
		                <a class='btn btn-success' href="{{ route('gestionar.secretaria.edit',$secretaria->id) }}">Editar</a>
		            </td>
		            <td>
			            {!! Form::open(['route' => ['gestionar.secretaria.destroy', $secretaria->id], 'method'=>'DELETE', 'class'=>'', 'id'=>'delete_secretaria']) !!}
			            	<button type="submit" class="btn btn-danger">Eliminar</button>
		                {!! Form::close() !!}
		            </td>
				</tr>
		    @endforeach
		    </tbody>
		    <tfoot>
			    <tr>
			        <th>ID</th>
					<th>Identificacion</th>				
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Email</th>
					<th>Celular</th>
					<th>Fecha Nacimiento</th>
					<th>Programa</th>
					<th>Editar</th>
					<th>Eliminar</th>					
			    </tr>
			</tfoot>
		</table>
	</div>
</div>	

resources/views/table/tabla-trabajo-de-grado.blade.php
<div class='box box-primary box-solid'>
	<div class="box-header">
		<h3 class="box-title">{{ Session::get('menu') }}</h3>
		<div class="box-tools pull-right">
			
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
		
	<div class="box-body table-responsive">
		<table id="tabla-tg" class='table table-bordered table-striped'>
		    <thead>
		    <tr>
		        <th>ID</th>
				<th>Fecha</th>				
				<th>Titulo</th>
				<th>Modalidad</th>
				<th>Director</th>
				<th>Estudiante1</th>
				<th>Estudiante2</th>
				<th>Jurado1</th>
				<th>Jurado2</th>
				<th>Estado</th>
				<th>Radicado</th>
				<th>Acta de Sustentacion</th>
				<th>Fecha de Sustentacion</th>
		    	@if(Auth::user()->type == 'Secretaria' || Auth::user()->type == 'Admin' || Auth::user()->type == 'Director' || Auth::user()->type == 'Decano')
		    	<th>Editar</th>
		    	<th>Proceso</th>
		    	@endif
		    </tr>
		    </thead>
		    <tbody>
		    @foreach ($trabajo_de_grado as $trabajoG)
				<tr>
					<td>{{ $trabajoG->id }}</td>
					<td>{{ $trabajoG->fecha }}</td>
					<td>{{ $trabajoG->titulo }}</td>
					<td>{{ $trabajoG->modalidadGrado }}</td>
					<td>{{ $trabajoG->director }}</td>
					<td>{{ $trabajoG->estudiante1 }}</td>
					<td>{{ $trabajoG->estudiante2 }}</td>
					<td>{{ $trabajoG->jurado1 }}</td>
					<td>{{ $trabajoG->jurado2 }}</td>
					<td>{{ $trabajoG->estado }}</td>
					<td>{{ $trabajoG->radicado }}</td>
					<td>{{ $trabajoG->actaSustentacion }}</td>
					<td>{{ $trabajoG->fechaSustentacion }}</td>
					@if(Auth::user()->type == 'Secretaria' || Auth::user()->type == 'Admin' || Auth::user()->type == 'Director' || Auth::user()->type == 'Decano')
					<td>
		                <a class='btn btn-success' href="{{ route('gestionar.trabajo-de-grado.edit',$trabajoG->id) }}">Editar</a>
		            </td>
		            <td>
		            	<a class='btn btn-primary' href="{{ route('gestionar.proceso-trabajo-de-grado.lista',$trabajoG->id) }}">Add</a>
		            </td>
		            @endif		            
				</tr>
		    @endforeach
		    </tbody>
		</table>
	</div>
</div>